# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='regex_modifiers',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
